# Generated by Django 5.1.4 on 2026-05-19 05:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('internship', 'Amaliyot (0-5 ball)'), ('part_time', 'Part-time (5-7 ball)'), ('full_time', 'Full-time (7-10 ball)')], max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('is_it_company', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('proof_url', models.URLField(blank=True)),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='accounts.studentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('assignment_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('activity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tutor_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discipline_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('base_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('penalty_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recovery_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employment_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gpa_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gpa_eligible', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Hisoblash kutilmoqda'), ('calculated', 'Hisoblangan'), ('approved', 'Tasdiqlangan'), ('grant_active', 'Grant faol'), ('grant_suspended', "Grant to'xtatilgan"), ('grant_cancelled', 'Grant bekor qilingan')], default='pending', max_length=20)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_scores', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_scores', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-final_score'],
            },
        ),
        migrations.CreateModel(
            name='GrantAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('rating', 'Reyting saralash'), ('interview', 'Suhbat'), ('final', 'Yakuniy')], max_length=20)),
                ('decision', models.CharField(choices=[('approved', 'Grant ajratildi'), ('waitlist', "Kutish ro'yxatida"), ('rejected', 'Rad etildi')], max_length=20)),
                ('interview_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('covers_tuition', models.BooleanField(default=True)),
                ('tuition_percentage', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('covers_dormitory', models.BooleanField(default=True)),
                ('covers_meals', models.BooleanField(default=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_allocations', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_allocations', to='accounts.studentprofile')),
                ('grant_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='grants.grantscore')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.AddIndex(
            model_name='grantscore',
            index=models.Index(fields=['-final_score'], name='grants_gran_final_s_9bdd76_idx'),
        ),
        migrations.AddIndex(
            model_name='grantscore',
            index=models.Index(fields=['semester', '-final_score'], name='grants_gran_semeste_6ed20e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grantscore',
            unique_together={('student', 'semester')},
        ),
    ]
