# Generated by Django 5.1.4 on 2026-05-19 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('competition', 'Musobaqa'), ('startup', 'Startup'), ('mentoring', 'Mentorlik'), ('cert_pdp', 'PDP Sertifikat'), ('cert_national', 'Milliy IT sertifikat'), ('cert_language', 'Til sertifikati'), ('cert_international', 'Xalqaro IT sertifikat'), ('volunteering', 'Volontyorlik'), ('soft_skills', 'Soft Skills'), ('networking', 'Networking'), ('project_participant', 'Loyiha ishtirokchisi'), ('direction_assistant', "Yo'nalish yordamchisi"), ('strategic_assistant', 'Strategik yordamchi')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('proof_url', models.URLField(blank=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='activity_proofs/')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.studentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('certificate_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('volunteering_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('other_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_scores', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_scores', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
