# Generated by Django 5.1.4 on 2026-05-19 05:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('light', 'Yengil (-1)'), ('medium', "O'rtacha (-3)"), ('heavy', "Og'ir (-5 to -15)")], max_length=10)),
                ('category', models.CharField(choices=[('late', 'Kechikish'), ('phone', 'Telefon ishlatish'), ('dormitory', 'Yotoqxona qoidalari'), ('absent', 'Sababsiz dars qoldirish'), ('ignore_warning', "Ogohlantirishni e'tiborsiz qoldirish"), ('rule_violation', 'Tartib qoidalarini buzish'), ('systematic_absent', 'Tizimli dars qoldirish'), ('discipline_issue', 'Intizomiy muammolar'), ('cheating', 'Akademik firibgarlik')], max_length=30)),
                ('points', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(0)])),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_penalties', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'Penalties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('recovery_points', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('assigned', 'Tayinlangan'), ('in_progress', 'Bajarilmoqda'), ('completed', 'Bajarildi'), ('failed', 'Bajarilmadi')], default='assigned', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recoveries', to=settings.AUTH_USER_MODEL)),
                ('penalty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='penalties.penalty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'Recoveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PenaltySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_penalty', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('total_recovery', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('net_penalty', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_summaries', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_summaries', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
