# Generated by Django 5.1.4 on 2026-05-19 05:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.CharField(choices=[('excellent', "A'lo"), ('good', 'Yaxshi'), ('average', "O'rtacha"), ('below_average', "O'rtachadan past"), ('poor', 'Yomon')], max_length=20)),
                ('participation', models.CharField(choices=[('excellent', "A'lo"), ('good', 'Yaxshi'), ('average', "O'rtacha"), ('below_average', "O'rtachadan past"), ('poor', 'Yomon')], max_length=20)),
                ('teamwork', models.CharField(choices=[('excellent', "A'lo"), ('good', 'Yaxshi'), ('average', "O'rtacha"), ('below_average', "O'rtachadan past"), ('poor', 'Yomon')], max_length=20)),
                ('initiative', models.CharField(choices=[('excellent', "A'lo"), ('good', 'Yaxshi'), ('average', "O'rtacha"), ('below_average', "O'rtachadan past"), ('poor', 'Yomon')], max_length=20)),
                ('overall_comment', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_feedbacks', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_feedbacks', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_honesty', models.DecimalField(decimal_places=2, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='TutorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_culture', models.DecimalField(decimal_places=1, help_text='Korporativ madaniyat va Etika (0-1)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('social_activity', models.DecimalField(decimal_places=1, help_text="Ijtimoiy va Ma'naviy-ma'rifiy faollik (0-1)", max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('soft_skills', models.DecimalField(decimal_places=1, help_text='Soft Skills va Shaxsiy rivojlanish (0-1)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('discipline', models.DecimalField(decimal_places=1, help_text="Intizom va Mas'uliyat (0-1)", max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('dormitory', models.DecimalField(decimal_places=1, help_text='Yotoqxona va Universitet hayoti (0-1)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('total_score', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_evaluations', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_evaluations', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'semester', 'evaluator')},
            },
        ),
    ]
