# Generated by Django 5.1.4 on 2026-05-19 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorevaluation',
            name='evaluator',
            field=models.ForeignKey(limit_choices_to={'role__in': ['tutor', 'komendant', 'manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL),
        ),
    ]
