# Generated by Django 5.1.4 on 2026-05-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher/Mentor'), ('tutor', 'Tutor'), ('komendant', 'Komendant'), ('manager', 'Unicron Manager'), ('parent', 'Parent'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
